parameters:

services:
    core.globals:
        class: core\Globals
    core.library.request.requestatomfactory:
        class: core\library\request\requestAtomFactory
    core.library.request.request:
        class: core\library\request\Request
        arguments: [ @core.globals, @core.library.request.requestatomfactory ]
    